# -*- coding: utf-8 -*-
"""Python Assignment (2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqV9_afLd6xuA7xbB56QkTqF9GiQw2vf
"""

#Question 1: Right Triangle Star Pattern
#Input the number of rows
n=5
for i in range(1,n+1): #Loop through rows
    for j in range(1,i+1): #Loop through columns
        print("*",end=" ")
    print()   #Move to the next line

#Question 2: Inverted Right Triangle Star Pattern
#Input the number of rows
n=5
for i in range(n,0,-1): #Loop through rows in reverse
    for j in range(0,i): #Loop through columns
        print("*",end=" ")
    print()  #Move to the next line

#Question 3: Triangle with repeating numbers
#Input the number of rows
n=4
for i in range(1,n+1): #Loop through rows
    for j in range(1,i+1): #Loop through columns
        print(i,end=" ") #Print the current row number
    print()  #Move to the next line

#Question 4: Triangle with asccending numbers in rows
#Input the number of rows
n=5
for i in range(1,n+1): #loop through rows
    for j in range(1,i+1): #Loop through numbers in each row
        print(j,end=" ") #Print the current number
    print()  #Move to the next line

#Question 5: Descending Number Triangle
#Input the number of rows
n=5
for i in range(n,0,-1): #Loop through rows in reverse
    for j in range(i,0,-1): #Loop through numbers in each row
        print(j,end=" ") #Print the current number in descending order
    print()  #Move to the next line

#Question 6: Hollow Square Pattern
#Input the number of rows
n=5
for i in range(0,n): #Loop through rows
    for j in range(0,n): #Loop through columns
        if i==0 or i==n-1 or j==0 or j==n-1:
            print("*",end=" ") #Print stars for the borders
        else:
            print(" ",end=" ") #Print spaces for the hollow part
    print() #Move to the next line

#Question 7: Diamond Pattern
#Input the number of rows
n=3
#Print the top half of the Diamond
for i in range(1,n+1):
    for j in range(0,n-i):
        print(end=" ") #Print leading spaces
    for j in range(1,i+1):
        print("*",end=" ") #Print stars
    print() #Move to the next line

#Print the bottom half of the Diamond
for i in range(1,n+1):
    for j in range(1,i+1):
        print(end=" ") #Print leading spaces
    for j in range(0,n-i):
        print("*",end=" ") #Print stars
    print()  #Move to the next line

#Question 8: Pascal's Triangle
#Input the number of rows
n=5
for i in range(n):  #Loop through rows
    coef=1
    for j in range(n-i-1):
        print(" ",end="") #Print leading spaces
    for j in range(i+1):
        print(coef,end=" ") #Print coefficients
        coef=coef*(i-j)//(j+1)  #Calculate the next coefficient
    print()  #Move to the next line

#Question 9: Sum of Even Numbers
def sum(n):
    sum_even=0
    for i in range(1,n): #Loop through even numbers
        if i%2==0:
            sum_even+=i #Add the current even number
    return sum_even
sum(10)

#Question 10: Factorial Calculation
def fact_calc(n):
    fact = 1
    for i in range(1,n+1): #Loop through numbers from 1 to n
        fact= fact*i  #Multiply to get factorial
    return fact
fact_calc(4)

#Question 11: Prime Numbers upto n
n = 20
for i in range(2, n + 1):  #Loop through numbers from 2 to n
    for j in range(2, int(i**0.5) + 1):  #Check if i is divisible by any number from 2 to sqrt(i)
        if i % j == 0:
            break
    else:
        print(i, end=" ")  #If the number is prime,print it

#Question 12: Vowel Counter
string = "hello world"
vowels = "aeiou"
count = 0
for i in string.lower():  # Loop through each character in the string
    if i in vowels:  # Check if it's a vowel
        count += 1
print("Number of vowels:", count)

#Question 13: Reverse a String
string= "anuska"
#Print the reverse of the string
print(string[::-1])

#Question 14: Substring Finder
string = "abc"
for i in range(len(string)):  # Loop through start indices
    for j in range(i + 1, len(string) + 1):  # Loop through end indices
        print(string[i:j])  # Print the substring

#Question 15: Character Frequency Counter
string = "shashini"
frequency = {}
for i in string:  # Loop through each character in the string
    frequency[i] = frequency.get(i, 0) + 1  # Count occurrences
for i, j in frequency.items():  # Loop through character-frequency pairs
    print(f"'{i}': {j}")

#Question 16: Fibonacci Sequence
def fibonacci(n):
    series=[]
    a,b=0,1
    for i in range(n): #Loop through n terms
        series.append(a) #Add the current term to the list
        a,b=b,a+b   #Update terms
    return series
fibonacci(10)

#Question 17: Multiplication Table
for i in range(1, 11):  # Loop through rows
    for j in range(1, 11):  # Loop through columns
        print(i*j, end="\t")  # Print the product
    print()  # Move to the next line

#Question 18: Matrix Pattern
n = 3
num = 1
for i in range(n):  # Loop through rows
    for j in range(n):  # Loop through columns
        print(num, end=" ")  # Print the current number
        num += 1  # Increment the number
    print()  # Move to the next line